import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navber from "@/app/components/navber"
import { ThemeProvider } from "next-themes"
import { type ThemeProviderProps } from "next-themes/dist/types"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          
          <div className="flex flex-row">
            <Navber/>
            <div className="">
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
